# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-04 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Aviator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseId', models.CharField(max_length=10)),
                ('house_name', models.CharField(max_length=100)),
                ('uptime', models.DateTimeField()),
                ('cpu_use', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AviatorConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_threshold', models.DecimalField(decimal_places=3, max_digits=6)),
                ('cpu_threshold', models.DecimalField(decimal_places=2, max_digits=5)),
                ('update_freq', models.IntegerField(default=300)),
                ('process_limit', models.IntegerField(default=5)),
                ('memory_greater_than', models.IntegerField(default=200)),
                ('aviator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lense.Aviator')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=3, max_digits=10)),
                ('avail', models.DecimalField(decimal_places=3, max_digits=10)),
                ('per_used', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessOnMemoryThreshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mem_used', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('process_Of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lense.Process')),
            ],
        ),
        migrations.CreateModel(
            name='TopCpuProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('process_Of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lense.Process')),
            ],
        ),
        migrations.CreateModel(
            name='TopMemoryProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('process_Of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lense.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Usb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=500)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='aviator',
            name='active_process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lense.Process'),
        ),
        migrations.AddField(
            model_name='aviator',
            name='memory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lense.Memory'),
        ),
        migrations.AddField(
            model_name='aviator',
            name='usb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lense.Usb'),
        ),
        migrations.AddField(
            model_name='alert',
            name='aviator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lense.Aviator'),
        ),
    ]
