# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviator',
            name='pi_did',
            field=models.CharField(default='P-549', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usb',
            name='name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
