# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseHealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttbehaviour',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restart',
            name='restart_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wifidisconnection',
            name='time_from',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wifidisconnection',
            name='time_to',
            field=models.CharField(max_length=100),
        ),
    ]
