# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-27 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HouseHealth', '0002_auto_20180319_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mqttbehaviour',
            name='restart',
        ),
        migrations.RemoveField(
            model_name='restart',
            name='house',
        ),
        migrations.RemoveField(
            model_name='wifidisconnection',
            name='restart',
        ),
        migrations.DeleteModel(
            name='CurrentHouseState',
        ),
        migrations.DeleteModel(
            name='MqttBehaviour',
        ),
        migrations.DeleteModel(
            name='Restart',
        ),
        migrations.DeleteModel(
            name='WifiDisconnection',
        ),
    ]
